config/routes.rb
Whiteboard::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :users
  resources :messages
  resources :courses
  resources :sections
  resources :assignment_grades do
     collection do
      get 'alter' # /assignment_grades/alter
    end
  end
  resources :assignment_uploads do
    collection do
      get 'download' # /assignment_uploads/download?assignment=13&user=6&name=routes.rb
    end
  end
  resources :assignment_config_uploads do
    collection do
      get 'download' # /assignment_config_uploads/download?assignment=13&name=routes.rb
    end
  end
  resources :assignment_grades
  resources :assignments do
    member do
      get 'files' # /assignments/1/files
      get 'configs' # /assignments/1/configs
      get 'students' # /assignments/1/students
    end
  end
  resources :attendances do
    collection do
      get 'alter' # /attendances/alter
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message, :date_sent, :reply_to, :appointment_timestamp, :receiver_deleted, :receiver_id, :receiver_read, :sender_deleted, :sender_id, :sent, :subject

  def self.find_user_messages(user_id)
    find(:all, :conditions => ['receiver_id = ? OR sender_id = ?', user_id, user_id])
  end

  # Same as find_user_messages but only returns the first message of each convo
  def self.find_user_conversations(user_id)
    find(:all, :conditions => ['reply_to is NULL AND (receiver_id = ? OR sender_id = ?)', user_id, user_id], :order => "date_sent DESC")
  end

  # Finds all the messages that are in reply to the starting message including
  # the starting message, and orders by date
  def self.find_conversation(message_id)
    find(:all, :conditions => ['reply_to = ? OR message_id = ?', message_id, message_id], :order => "date_sent ASC")
  end

  # Find all the users in the conversation
  def self.find_convo_user_ids(message_id)
    # messages = select("DISTINCT ON (sender_id, receiver_id) *").find(:all, :conditions => ['reply_to = ? OR message_id = ?', message_id, message_id])
    first_message = find(:first, :conditions => ['message_id = ?', message_id])
    users = [first_message.sender_id, first_message.receiver_id]
  end

end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base

  # GET /messages
  # GET /messages.json
  def index
    authorize! :read, Message
    @messages = Message.find_user_conversations(current_user.id)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    authorize! :read, Message
    @messages = Message.find_conversation(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new
    authorize! :create, @message

    # If this is a reply to an already created convo
    if params.has_key?(:reply)
      @first_convo_message = Message.find(params[:reply])
      @reply_to = @first_convo_message.message_id
      @first_convo_message.subject = 'Re: ' + @first_convo_message.subject

      # Figure out who the receiver is in this conversation. If
      # only one person then it's ourself, otherwise we need to
      # query for a distinct list of convo participants and grab
      # the one whose id does not match our own.
      @participant_ids = [@first_convo_message.sender_id, @first_convo_message.receiver_id]

      # Assume it's the same person replying to themselves, although
      # this is probably not true and will be corrected below if so
      @receiver_id = @participant_ids.first

      # Find the person we are replying to
      @participant_ids.each do |user_id|
        if user_id != current_user.id
          @receiver_id = user_id
          break
        end
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    authorize! :update, Message
    redirect_to messages_path
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    authorize! :create, @message
    @message.date_sent = DateTime.now

    if params.has_key?(:appointment_timestamp)
      if params[:appointment_timestamp].match(/(\d{2})\/(\d{2})\/(\d{4})\s(\d{2}):(\d{2})\s(am|pm)/i)
        month, day, year, hours, minutes, ampm = $1.to_i, $2.to_i, $3.to_i, $4.to_i, $5.to_i, $6

        if hours == 12 && ampm == 'am'
          hours = 0
        elsif ampm == 'pm'
          hours += 11
        end

        @message.appointment_timestamp = Time.new(year, month, day, hours, minutes, 0, "-01:00")
      end
    end

    error = '';
    is_reply = false

    if params[:message].has_key?(:receiver_id)
      is_reply = true
    end

    if @message.subject.length < 1 || @message.message.length < 1
      error = 'You must have a subject and a message.'
    else
      @receiver_id = nil

      if params[:message].has_key?(:receiver_id)
        @receiver_id = params[:message][:receiver_id]
      else
        @receiver_id = User.find_id_by_email(params[:receiver_email])
      end

      if !@receiver_id.nil?
        @message.receiver_id = @receiver_id
      else
        error = 'The user with the email address "' + params[:receiver_email] + '" does not exist.'
      end
    end

    respond_to do |format|
      if !@receiver_id.nil? && @message.save
        if is_reply
          format.html { redirect_to message_path(@message.reply_to) }
        else
          format.html { redirect_to @message }
        end
      else
        flash[:error] = error

        if is_reply
          @first_convo_message = Message.new(params[:message])
          @reply_to = @first_convo_message.reply_to
          @receiver_id = params[:message][:receiver_id]
        end

        format.html { render action: "new" }
      end
    end
  end

  # # PUT /messages/1
  # # PUT /messages/1.json
  def update
    authorize! :update, Message
    redirect_to messages_path
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    authorize! :destroy, @message

    if current_user.id == @message.sender_id
      @message.sender_deleted = true
    else
      @message.receiver_deleted = true
    end

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :sender_id, :value => current_user.user_id %>

    <% if @first_convo_message %>
      <%= f.hidden_field :receiver_id, :value => @receiver_id %>
      <%= f.hidden_field :reply_to, :value => @reply_to %>
      <%= f.input :subject, :input_html => { :value => @first_convo_message.subject } %>
    <% else %>
      <%= label_tag(:receiver_email, "Email") %>
      <%= text_field_tag(:receiver_email) %>
      <%= label_tag(:appointment_timestamp, "Appointment Time") %>
      <%= text_field_tag(:appointment_timestamp) %>
      <%= f.input :subject %>
    <% end %>

    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

<script type="text/javascript">

$(document).ready(function() {
  $('#appointment_timestamp').datetimepicker({
    minDate: 0,
    dateFormat: "mm/dd/yy",
    timeFormat: "hh:mm tt"
  });
});

</script>

app/views/messages/_new.html.erb
<h1>New Message</h1>

<hr>

<%= render 'form' %>

app/views/messages/_reply.html.erb
<h1><%= @first_convo_message.subject %></h1>

<hr>

<%= render 'form' %>

app/views/messages/_subnavbar.html.erb
<li>
  <%= link_to 'Messages', messages_path %>
  <span class="arrow">
    <span></span>
  </span>
</li>

<% if params[:action] == 'new' %>

  <li>
    <%= link_to 'New', new_message_path %>
    <span class="arrow">
      <span></span>
    </span>
  </li>

<% end %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<hr>

<table class="table table-striped">
<% @messages.each do |message| %>
  <tr>
    <td width="20%"><%= link_to User.find_name_by_user_id(message.receiver_id), user_path(message.receiver_id) %></td>
    <td width="80%"><%= link_to message.subject, message %></td>
  </tr>
<% end %>
</table>

<a href="<%= new_message_path %>">
  <input class="btn btn-primary" type="button" value="Create New Message" />
</a>

app/views/messages/new.html.erb
<% if params.has_key?(:reply) %>
  <%= render 'reply' %>
<% else %>
  <%= render 'new' %>
<% end %>

app/views/messages/show.html.erb
<h1><%= @messages.first.subject %></h1>

<hr>

<div id="message-convo">
<% @messages.each do |message| %>
  <div class="box">
    <span class="author">
      <span class"left">
        <% if message.sender_id == current_user.id %>
          Me
        <% else %>
          <% user = User.find(message.sender_id) %>
          <%= link_to user.name, user_path(user.user_id) %>
        <% end %>
      </span>
      <% if !message.appointment_timestamp.nil? %>
        <span class="right">
          Appointment: <%= message.appointment_timestamp.strftime('%B %d, %Y at %l:%M %p') %>
        </span>
      <% end %>
    </span>
    <span class="message">
      <%= simple_format(message.message) %>
    </span>
    <div class="clear"></div>
  </div>
<% end %>
</div>

<a href="<%= new_message_path(:reply => @messages.first.message_id) %>">
  <input class="btn btn-primary" type="button" value="Reply" />
</a>