config/routes.rb
Whiteboard::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :users
  resources :messages
  resources :courses
  resources :sections
  resources :assignment_grades do
     collection do
      get 'alter' # /assignment_grades/alter
    end
  end
  resources :assignment_uploads do
    collection do
      get 'download' # /assignment_uploads/download?assignment=13&user=6&name=routes.rb
    end
  end
  resources :assignment_config_uploads do
    collection do
      get 'download' # /assignment_config_uploads/download?assignment=13&name=routes.rb
    end
  end
  resources :assignment_grades
  resources :assignments do
    member do
      get 'files' # /assignments/1/files
      get 'configs' # /assignments/1/configs
      get 'students' # /assignments/1/students
    end
  end
  resources :attendances do
    collection do
      get 'alter' # /attendances/alter
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :due_date, :name, :description, :highest_grade_value, :section_id, :type_id, :weight
  belongs_to :section

  # Return all assignments in the given course section
  def self.find_by_section_id(section_id)
    where(:section_id => section_id)
  end

  # Return all assignments in all the course sections
  def self.find_all_by_course_id(course_id)
    sections = Section.find_all_by_course_id
    where("section_id in (?)", sections)
  end

  def get_type_name
    AssignmentType.find_name_by_type_id(self.type_id)
  end

  def get_name
    (self.name != nil) ? self.name : 'Unnamed'
  end

  def get_description
    (self.description != nil && self.description.match(/\S/)) ? self.description : 'No description.'
  end

  def formatted_due_date(format)
    if !self.due_date.nil?
      return self.due_date.strftime(format)
    else
      return 'TBA'
    end
  end

end

app/models/assignment_type.rb
class AssignmentType < ActiveRecord::Base
  attr_accessible :name
  belongs_to :assignment

  def self.find_name_by_type_id(type_id)
    find(:first, :conditions => ['type_id = ?', type_id]).name
  end

  def to_s
    self.name
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :get_grade_type_select_options

  def get_grade_type_select_options
    options = []

    AssignmentType.all.each do |type|
      options << [type.name, type.type_id]
    end

    return options
  end

  # GET /assignments/1/students
  def students
    authorize! :update, AssignmentConfigUpload
    @assignment = Assignment.find(params[:id])
    authorize! :read, @assignment
    @course = Course.find_by_section_id(@assignment.section_id)
    @students = Section.find_students_in_section(@assignment.section_id)
  end

  # GET /assignments/1/configs
  # Has to be plural since "config" is a predfined method
  def configs
    authorize! :update, AssignmentConfigUpload
    @assignment = Assignment.find(params[:id])
    authorize! :read, @assignment
    @course = Course.find_by_section_id(@assignment.section_id)
  end

  # GET /assignments/1/files
  def files
    authorize! :update, AssignmentUpload
    @assignment = Assignment.find(params[:id])
    authorize! :read, @assignment

    # If a professor/ta viewing a student's upoaded files
    if params.has_key?(:user) && can?(:manage, AssignmentGrade)
      @user_id = params[:user]
    else
      @user_id = current_user.id
    end

    @user = User.find(@user_id)
    @course = Course.find_by_section_id(@assignment.section_id)
  end

  # GET /assignments
  # GET /assignments.json
  def index
    authorize! :read, Assignment

    if params.has_key?(:course)
      @course = Course.find(params[:course])

      if is_student?
        @sections = []
        @sections << User.find_user_section_by_course_id(current_user.id, @course.course_id)
      else
        @sections = User.find_professor_sections_in_course(current_user.id, @course.course_id)
      end

      @assignments = {}

      @sections.each do |section|
        @assignments[section.section_id] = {
          :section => section,
          :assignments => Assignment.find_by_section_id(section.section_id)
        }
      end
    else
      if is_student?
        @sections = User.find_student_sections(current_user.id)
      else
        @sections = User.find_professor_sections(current_user.id)
      end

      # Find all the courses associated with the sections found
      @courses = {}
      @sections.each do |section|
        if !@courses.has_key?(section.section_id)
          @courses[section.section_id] = Course.find_by_section_id(section.section_id)
        end
      end

      # Find all assignments in each section
      @assignments = {}
      @sections.each do |section|
        @assignments[section.section_id] = {
          :course => @courses[section.section_id],
          :section => section,
          :assignments => Assignment.find_by_section_id(section.section_id)
        }
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])
    authorize! :read, @assignment
    @course = Course.find_by_section_id(@assignment.section_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    if !params.has_key?(:section)
      redirect_to assignments_url and return
    end

    @assignment = Assignment.new
    authorize! :create, @assignment

    @section_id = params[:section]
    @course = Course.find_by_section_id(@section_id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
    authorize! :update, @assignment
    @section_id = @assignment.section_id
    @course = Course.find_by_section_id(@section_id)
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])
    authorize! :create, @assignment   

    if params[:assignment].has_key?(:due_date)
      if params[:assignment][:due_date].match(/(\d{2})\/(\d{2})\/(\d{4})\s(\d{2}):(\d{2})\s(am|pm)/i)
        month, day, year, hours, minutes, ampm = $1.to_i, $2.to_i, $3.to_i, $4.to_i, $5.to_i, $6
        
        if hours == 12 && ampm == 'am'
          hours = 0
        elsif ampm == 'pm'
          hours += 11
        end

        @assignment.due_date = Time.new(year, month, day, hours, minutes, 0, "-00:00")
      end
    end

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])
    authorize! :update, @assignment

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    authorize! :destroy, @assignment
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignments.html.erb
<h1><%= @course.name %> Assignments</h1>

<hr>

<table id="assignments" class="table">
<% @assignments.each do |key, section_assignments| %>
  <% if is_professor? %>
    <tr class="course_section_title_row section_<%= @assignments[key][:section].section_id %>">
      <td width="70%">
        <b>Section <%= @assignments[key][:section].number %></b>
      </td>
      <td width="30%" style="text-align: center;">
        <b><%= link_to 'Create New Assignment', new_assignment_path(:section => @assignments[key][:section].section_id) %></b>
      </td>
    </tr>
  <% end %>
  <tr class="course_section_container_row">
    <td colspan="2">
      <table class="table table-striped">
        <% if @assignments[key][:assignments].length < 1 %>
          <tr>
            <td colspan="6">
              No assignments.
            </td>
          </tr>
        <% else %>
          <% @assignments[key][:assignments].each do |assignment| %>
            <tr>
              <td width="25%"><%= link_to assignment.get_name, assignment_path(assignment) %></td>
              <td width="15%"><%= assignment.get_type_name %></td>
              <td width="20%"><%= assignment.formatted_due_date(date_page_format) %></td>
              <td width="5%"><%= assignment.highest_grade_value %></td>
              <td width="5%"><%= assignment.weight %></td>
              <td width="30%" style="text-align: center;">
                <% if is_student? %>
                  <%= link_to 'Files', files_assignment_path(assignment) %>
                <% elsif is_professor? %>
                  <%= link_to 'Files', students_assignment_path(assignment) %> |
                  <%= link_to 'Config', configs_assignment_path(assignment) %> |
                  <%= link_to 'Edit', edit_assignment_path(assignment) %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </td>
  </tr>
<% end %>
</table>

app/views/assignments/_config_upload_form.html.erb
  <%= form_for AssignmentConfigUpload.new, :url => assignment_config_uploads_path(:assignment_id => params[:id]), :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div>
        <%= f.hidden_field :assignment_id, :value => params[:id] %>
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :assignment_config_upload %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  {% if(file.files && file.files[0]) { %}
  {%     file = file.files[0]; %}
  {% } %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  {% if(file.files && file.files[0]) { %}
  {%     file = file.files[0]; %}
  {% } %}
  {% /*var abc = ''; for(var key in file) { abc += key + ': ' + file[key] + '\n'; } alert(abc);*/ %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">

$(function() {
  // Initialize the jQuery File Upload widget
  $('#fileupload').fileupload();

  // Load existing files:
  $.getJSON($('#fileupload').prop('action'), function(files) {

    var fu = $('#fileupload').data('blueimpFileupload'), template;
    fu._adjustMaxNumberOfFiles(-files.length);
    template = fu._renderDownload(files).appendTo($('#fileupload .files'));

    // Force reflow
    fu._reflow = fu._transition && template.length && template[0].offsetWidth;
    template.addClass('in');
    $('#loading').remove();
  });
});

</script>

app/views/assignments/_courses.html.erb
<h1>Assignments</h1>

<hr>

<table id="assignments" class="table">
<% @assignments.each do |key, section_assignments| %>
  <tr class="course_section_title_row section_<%= @assignments[key][:section].section_id %>">
    <td width="70%" class="course_section_name">
        <b>
          <% link_text = @assignments[key][:course].name %>
          <% link_text += ' - Section ' + @assignments[key][:section].number.to_s if is_professor? %>
          <%= link_to link_text, assignments_path(:course => @assignments[key][:course].course_id) %>
        </b>
    </td>
    <td width="30%" style="text-align: center;">
      <% if is_professor? %>
        <b><%= link_to 'Create New Assignment', new_assignment_path(:section => @assignments[key][:section].section_id) %></b>
      <% end %>
    </td>
  </tr>
  <tr class="course_section_container_row">
    <td colspan="2">
      <div class="slider">
        <table class="table table-striped">
          <% if @assignments[key][:assignments].length < 1 %>
            <tr>
              <td colspan="6">
                No assignments.
              </td>
            </tr>
          <% else %>
            <% @assignments[key][:assignments].each do |assignment| %>
              <tr>
                <td width="25%"><%= link_to assignment.get_name, assignment_path(assignment) %></td>
                <td width="15%"><%= assignment.get_type_name %></td>
                <td width="20%"><%= assignment.formatted_due_date(date_page_format) %></td>
                <td width="5%"><%= assignment.highest_grade_value %></td>
                <td width="5%"><%= assignment.weight %></td>
                <td width="30%" style="text-align: center;">
                  <% if is_student? %>
                    <%= link_to 'Files', files_assignment_path(assignment) %>
                  <% elsif is_professor? %>
                    <%= link_to 'Files', students_assignment_path(assignment) %> |
                    <%= link_to 'Config', configs_assignment_path(assignment) %> |
                    <%= link_to 'Edit', edit_assignment_path(assignment) %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </td>
  </tr>
<% end %>
</table>

<script type="text/javascript">

// Remember which assignment sections have been expanded
var assignment_slider_cache = null;
var local_storage_key = 'assignment_section_collapse';
var collapsed = 1;
var visible = 0;

$(document).ready(function() {
  var data = window.localStorage[local_storage_key];

  if(data) {
    assignment_slider_cache = $.parseJSON(data);
  }
  else {
    assignment_slider_cache = {};
  }

  $('#assignments tr.course_section_title_row').each(function() {
    var section_id = $(this).attr('class').match(/section_\d+/i)[0].split("_")[1];

    if(assignment_slider_cache.hasOwnProperty(section_id) &&
      assignment_slider_cache[section_id] == visible) {
      $(this).next().find('div.slider').show();
    }
  });

  $('#assignments tr.course_section_title_row > td').css('cursor','pointer').click(function() {
    var divslider = $(this).parent().next().find('div.slider');
    var section_id = $(this).parent().attr('class').match(/section_\d+/i)[0].split("_")[1];

    if(divslider.is(':hidden')) {
      divslider.slideDown('fast');
      assignment_slider_cache[section_id] = visible;
    }
    else {
      divslider.slideUp('fast');
      assignment_slider_cache[section_id] = collapsed;
    }

    window.localStorage[local_storage_key] = JSON.stringify(assignment_slider_cache);
  });

  // Stop the above click event from happening if a link within is clicked
  $("#assignments a").click(function(event){
    event.stopPropagation();
  });  
});

</script>

app/views/assignments/_subnavbar.html.erb
<li>
  <%= link_to 'Assignments', assignments_path %>
  <span class="arrow">
    <span></span>
  </span>
</li>

<% if !@course.nil? %>
  <li>
    <%= link_to @course.name, assignments_path(:course => @course.course_id) %>
    <span class="arrow">
      <span></span>
    </span>
  </li>

  <% if params[:action] != 'new' %>

    <% if !@assignment.nil? %>
      <li>
        <%= link_to @assignment.get_name, assignment_path(@assignment) %>
        <span class="arrow">
          <span></span>
        </span>
      </li>
    <% end %>

    <% if params[:action] == 'edit' %>

      <li>
        <%= link_to 'Edit', edit_assignment_path(@assignment) %>
        <span class="arrow">
          <span></span>
        </span>
      </li>

    <% elsif params[:action] == 'files' %>

      <li>
        <%= link_to 'Files', files_assignment_path(@assignment) %>
        <span class="arrow">
          <span></span>
        </span>
      </li>

    <% elsif params[:action] == 'configs' %>

      <li>
        <%= link_to 'Configuration', configs_assignment_path(@assignment) %>
        <span class="arrow">
          <span></span>
        </span>
      </li>

    <% elsif params[:action] == 'students' %>

      <li>
        <%= link_to 'Student Files', students_assignment_path(@assignment) %>
        <span class="arrow">
          <span></span>
        </span>
      </li>

    <% end %>

  <% else %>

    <li>
      <%= link_to 'New', new_assignment_path(:section => @section_id) %>
      <span class="arrow">
        <span></span>
      </span>
    </li>
  <% end %>

<% end %>

app/views/assignments/_upload_form.html.erb
  <%= form_for AssignmentUpload.new, :url => assignment_uploads_path(:assignment_id => params[:id], :user_id => @user_id), :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div>
        <%= f.hidden_field :assignment_id, :value => params[:id] %>
        <%= f.hidden_field :user_id, :value => @user_id %>
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :assignment_upload %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  {% if(file.files && file.files[0]) { %}
  {%     file = file.files[0]; %}
  {% } %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  {% if(file.files && file.files[0]) { %}
  {%     file = file.files[0]; %}
  {% } %}
  {% /*var abc = ''; for(var key in file) { abc += key + ': ' + file[key] + '\n'; } alert(abc);*/ %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">

$(function() {
  // Initialize the jQuery File Upload widget
  $('#fileupload').fileupload();

  // Load existing files:
  $.getJSON($('#fileupload').prop('action'), function(files) {

    var fu = $('#fileupload').data('blueimpFileupload'), template;
    fu._adjustMaxNumberOfFiles(-files.length);
    template = fu._renderDownload(files).appendTo($('#fileupload .files'));

    // Force reflow
    fu._reflow = fu._transition && template.length && template[0].offsetWidth;
    template.addClass('in');
    $('#loading').remove();
  });
});

</script>

app/views/assignments/configs.html.erb
<h1><%= @assignment.get_name %> Configuration</h1>

<hr>

<%= render 'config_upload_form' %>

app/views/assignments/edit.html.erb
<h1>Edit <%= @assignment.get_name %></h1>

<hr>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h1><%= @assignment.get_name %></h1>

<hr>

<p>
  <b>Type:</b>
  <%= @assignment.get_type_name %>
</p>

<p>
  <b>Due Date:</b>
  <%= @assignment.formatted_due_date('%B %d, %Y at %l:%M %p') %>
</p>

<p>
  <b>Highest Grade Value:</b>
  <%= @assignment.highest_grade_value %>
</p>

<p>
  <b>Weight:</b>
  <%= @assignment.weight %>
</p>

<div class="box">
  <%= simple_format(@assignment.get_description) %>
</div>

<a href="<%= files_assignment_path(@assignment) %>">
  <input class="btn btn-primary" type="button" value="Files" />
</a>

<% if can? :manage, AssignmentConfigUpload %>
  <a href="<%= configs_assignment_path(@assignment) %>">
    <input class="btn btn-primary" type="button" value="Config" />
  </a>
  <a href="<%= students_assignment_path(@assignment) %>">
    <input class="btn btn-primary" type="button" value="Student Files" />
  </a>
<% end %>

<% if can? :update, @assignment %>
  <a href="<%= edit_assignment_path(@assignment) %>">
    <input class="btn btn-primary" type="button" value="Edit" />
  </a>
<% end %>

app/views/assignments/students.html.erb
<h1><%= @assignment.name %> Student Files</h1>

<hr>

<table class="table table-striped">
  <% @students.each do |student| %>
    <tr>
      <td><%= link_to student.name, files_assignment_path(@assignment, :user => student.user_id) %></td>
    </tr>
  <% end %>
</table>