config/routes.rb
Whiteboard::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :users
  resources :messages
  resources :courses
  resources :sections
  resources :assignment_grades do
     collection do
      get 'alter' # /assignment_grades/alter
    end
  end
  resources :assignment_uploads do
    collection do
      get 'download' # /assignment_uploads/download?assignment=13&user=6&name=routes.rb
    end
  end
  resources :assignment_config_uploads do
    collection do
      get 'download' # /assignment_config_uploads/download?assignment=13&name=routes.rb
    end
  end
  resources :assignment_grades
  resources :assignments do
    member do
      get 'files' # /assignments/1/files
      get 'configs' # /assignments/1/configs
      get 'students' # /assignments/1/students
    end
  end
  resources :attendances do
    collection do
      get 'alter' # /attendances/alter
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!
  helper_method :display_courses

  # GET /courses
  # GET /courses.json
  def index
    authorize! :read, Course

    if is_student?
      @course_sections = Course.find_student_courses(current_user.id)
    else
      @course_sections = Course.find_professor_courses(current_user.id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    if !params.has_key?(:section)
      redirect_to courses_path and return
    end

    @course = Course.find(params[:id])
    authorize! :read, @course
    @section = Section.find(params[:section])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    authorize! :create, Course
    redirect_to courses_path
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    authorize! :update, @course
    redirect_to @course
  end

  # POST /courses
  # POST /courses.json
  def create
    authorize! :create, Course
    redirect_to courses_path
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    authorize! :update, Course
    redirect_to courses_path
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize! :destroy, Course
    redirect_to courses_path
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_subnavbar.html.erb
<li>
  <%= link_to 'Courses', courses_path %>
  <span class="arrow">
    <span></span>
  </span>
</li>

<% if !@course.nil? %>
<li>
  <%= link_to @course.name, course_path(@course.course_id, :section => params[:section]) %>
  <span class="arrow">
    <span></span>
  </span>
</li>
<% end %>

app/views/courses/index.html.erb
<h1>Courses<h1>

<hr>

<div id="courses" class="blocks-buttons">
  <% @course_sections.each do |cs| %>
    <div class="item" id="course_<%= cs[:course].course_id %>_section_<%= cs[:section].section_id %>">
      <div class="valign">
        <div class="title">
          <%= link_to cs[:course].number + ' ' + cs[:course].name, course_path(cs[:course], :section => cs[:section].section_id) %>
        </div>
        <div class="content">
          <% if is_professor? %>
            <%= link_to 'Attendance', attendances_path(:section => cs[:section].section_id, :date => DateTime.now.strftime(date_url_format)) %><br />
          <% end %>
          <%= link_to 'Assignments', assignments_path(:course => cs[:course].course_id) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<script type="text/javascript">

$(document).ready(function() {
  $('#courses .item').click(function() {
    var course_id = $(this).attr('id').split('_')[1];
    var section_id = $(this).attr('id').split('_')[3];
    location.href = '/courses/' + course_id + '?section=' + section_id;
  })
});

</script>

app/views/courses/show.html.erb
<h1><%= @course.number %> <%= @course.name %></h1>

<hr>

<p class="top-right">
  <b>Section <%= @section.number %></b>
</p>

<p>
  <%= simple_format(@section.description) %>
</p>

<a href="<%= assignments_path(:course => @course.course_id) %>">
  <input class="btn btn-primary" type="button" value="Assignments" />
</a>

<% if is_professor? %>
  <a href="<%= attendances_path(:date => DateTime.now.strftime(date_url_format), :section => @section.section_id) %>">
    <input class="btn btn-primary" type="button" value="Attendance" />
  </a>
  <a href="<%= edit_section_path(params[:section], :course => @course.course_id) %>">
    <input class="btn btn-primary" type="button" value="Edit" />
  </a>
<% end %>