config/routes.rb
Whiteboard::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :users
  resources :messages
  resources :courses
  resources :sections
  resources :assignment_grades do
     collection do
      get 'alter' # /assignment_grades/alter
    end
  end
  resources :assignment_uploads do
    collection do
      get 'download' # /assignment_uploads/download?assignment=13&user=6&name=routes.rb
    end
  end
  resources :assignment_config_uploads do
    collection do
      get 'download' # /assignment_config_uploads/download?assignment=13&name=routes.rb
    end
  end
  resources :assignment_grades
  resources :assignments do
    member do
      get 'files' # /assignments/1/files
      get 'configs' # /assignments/1/configs
      get 'students' # /assignments/1/students
    end
  end
  resources :attendances do
    collection do
      get 'alter' # /attendances/alter
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

end

app/views/layouts/_headernav.html.erb
<ul class="login">
  <% if user_signed_in? %>
    <li><%= current_user.name %></li>
  <% else %>
    <li>Welcome, Guest</li>
  <% end %>
</ul>

<ul class="nav">
  <% if user_signed_in? %>

    <% if is_admin? %>
      <li>
        <%= link_to 'Admin', admin_root_path %>
      </li>
    <% end %>

    <li>
      <%= link_to 'Messages', messages_path %>
    </li>
    <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method =>'delete' %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Admin', admin_root_path %>
    </li>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Forgot Password', new_user_password_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_mobilenav.html.erb
<ul class="nav">
  <% if user_signed_in? %>

    <li>
      <%= link_to 'Home', root_path %>
    </li>

    <% if can? :read, Course %>
      <li class="courses_controller">
        <%= link_to 'Courses', courses_path %>
      </li>
    <% end %>

    <% if can? :read, Assignment %>
      <li class="assignments_controller">
        <%= link_to 'Assignments', assignments_path %>
      </li>
    <% end %>

    <% if can? :read, Attendance %>
      <li class="attendances_controller">
        <%= link_to 'Attendance', attendances_path %>
      </li>
    <% end %>

    <% if can? :read, AssignmentGrade %>
      <li class="assignment_grades_controller">
        <%= link_to 'Gradebook', assignment_grades_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<ul class="nav">
  <li>
    <a href="/" class="first">Whiteboard</a>
    <span class="arrow">
      <span></span>
    </span>
  </li>
  <%= render :partial => "subnavbar" %>
</ul>

<ul class="date">
  <li><%= DateTime.now.strftime(date_page_format) %></li>
</ul>

app/views/layouts/_sidebar.html.erb
<ul class="nav">
  <% if user_signed_in? %>

    <% if can? :read, Course %>
      <li class="courses_controller">
        <%= link_to 'Courses', courses_path %>
      </li>
    <% end %>

    <% if can? :read, Assignment %>
      <li class="assignments_controller">
        <%= link_to 'Assignments', assignments_path %>
      </li>
    <% end %>

    <% if can? :read, Attendance %>
      <li class="attendances_controller">
        <%= link_to 'Attendance', attendances_path %>
      </li>
    <% end %>

    <% if can? :read, AssignmentGrade %>
      <li class="assignment_grades_controller">
        <%= link_to 'Gradebook', assignment_grades_path %>
      </li>
    <% end %>
  <% else %>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Forgot Password', new_user_password_path %>
    </li>
  <% end %>
</ul>
<div class="clear" style="height: 300px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Whiteboard" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Whiteboard" %>">
    <%= stylesheet_link_tag "application", :media => "all and (min-width: 500px)" %>
    <%= stylesheet_link_tag "mobileApp", :media => "all and (max-width: 499px)" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= javascript_tag do %>
      var controller_name = "<%= controller_name %>";
      $(document).ready(function() { selectSidebarButton(controller_name); });
    <% end %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <header id="headernav">
      <%= render 'layouts/headernav' %>
      <div id = "mobilenav">
        <%= render 'layouts/mobilenav' %>
      </div>
      <div class="clear"></div>
    </header>
    <div id="main" role="main">      
      <div id="navbar" class="body-row">
        <%= render 'layouts/navbar' %>
        <div class="clear"></div>
      </div>
      <div id="wrapper" class="body-row">
        <div id="content">
          <div class="bootstrap-styles bootstrap-padding">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <div id="sidebar">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </body>
</html>